---
title: "simulation"
author: "Aiying Huang"
date: "2023-11-02"
output: html_document
---

## Simulate sample mean and sd
```{r}
library(tidyverse)
library(rvest)
```


```{r}
sim_mean_sd=function(n_obs, mu=5, sigma=1){
  
  x_vec=rnorm(n=n_obs, mean=mu, sd=sigma)
  
  tibble(
    mean=mean(x_vec),
    sd=sd(x_vec)
  )
}
```

Let's see what this does.

```{r}
sim_mean_sd(n_obs=30)
```

Let's iterate to see how this works UNDER REPEATED SAMPLING!!!

```{r}
output=vector("list",length=100)

for (i in 1:100){
  
  output[[i]]=sim_mean_sd(n_obs=30)
  
}

sim_results=
  bind_rows(output)
sim_results|>
  ggplot(aes(x=mean))+geom_density()
```
```{r}
sim_results|>
  summarize(
    mu_hat=mean(mean),
    sd_hat=sd(mean)#should be about 1/sqrt(30)=0.1825
)
```
use a map function

```{r}
sim_result_df=
  expand_grid(
    sample_size=c(30,60,120,240),
    iter=1:1000
  )|>
  mutate(estimate_df=map(sample_size,sim_mean_sd))|>
  unnest(estimate_df)

sim_result_df|>
  mutate(
    sample_size=str_c("n= ",sample_size),#make it as a character
    sample_size=fct_inorder(sample_size)
  )|>
  ggplot(aes(x=sample_size,y=mean))+
  geom_boxplot()
```
```{r}
sim_mean_sd=function(n_obs, true_p=.9){
  
  x_vec=rbinom(n=n_obs,size=1, prob=true_p)
  
  tibble(
    mean=mean(x_vec),
    sd=sd(x_vec)
  )
}
```
```{r}
sim_result_df=
  expand_grid(
    sample_size=c(30,60,120,240),
    iter=1:1000
  )|>
  mutate(estimate_df=map(sample_size,sim_mean_sd))|>
  unnest(estimate_df)

sim_result_df|>
  mutate(
    sample_size=str_c("n= ",sample_size),#make it as a character
    sample_size=fct_inorder(sample_size)
  )|>
  ggplot(aes(x=sample_size,y=mean))+
  geom_boxplot()
#when n_obs is small the distribution is skewed, however...
```

```{r}

```







